#!/usr/bin/env bash
# Point the app at a Supabase project.
# Usage: bash scripts/point-to-project.sh <PROJECT_REF> <PUBLISHABLE_KEY>
set -euo pipefail

REF="${1:?PROJECT_REF required (the xxxx in https://xxxx.supabase.co)}"
KEY="${2:?PUBLISHABLE_KEY required (sb_publishable_... or anon JWT)}"
URL="https://${REF}.supabase.co"

ROOT="$(cd "$(dirname "$0")/.." && pwd)"

cat > "$ROOT/.env" <<EOF
VITE_SUPABASE_PROJECT_ID="${REF}"
VITE_SUPABASE_PUBLISHABLE_KEY="${KEY}"
VITE_SUPABASE_URL="${URL}"
EOF

cat > "$ROOT/src/integrations/supabase/client.ts" <<EOF
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL ?? "${URL}";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ?? "${KEY}";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
EOF

if [ -f "$ROOT/supabase/config.toml" ]; then
  sed -i '' "s/^project_id = .*/project_id = \"${REF}\"/" "$ROOT/supabase/config.toml"
fi

echo "Pointed app at ${URL}"
