// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://usunoalilbxtzdqmhvcq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVzdW5vYWxpbGJ4dHpkcW1odmNxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwMzc5MDUsImV4cCI6MjA3MjYxMzkwNX0.liHRbgh_7MHAv81HwKerZVV1HBRSksafnxaGYlAhd2U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});